import { findSubcategory, seedPosting } from "@/lib/posting"
import type { CategoryId, Listing } from "@/lib/types"

export const categoryImage: Record<CategoryId, string> = {
  vehicles: "/listings/sedan.jpg",
  property: "/listings/house2.jpg",
  electronics: "/listings/iphone.jpg",
  home: "/listings/sofa.jpg",
  jobs: "/listings/laptop.jpg",
  services: "/listings/tools.jpg",
  business: "/listings/container.jpg",
  agriculture: "/listings/farm.jpg",
  fashion: "/listings/clothes.jpg",
  health: "/listings/clinic.jpg",
  education: "/listings/books.jpg",
  community: "/listings/community.jpg",
}

type Seed = Listing

function listing(entry: Seed): Seed {
  const posted = seedPosting[entry.id]
  return {
    currency: "USD",
    ...entry,
    subcategory: posted?.subcategory ?? entry.subcategory,
    details: posted?.details ?? entry.details,
  }
}

export const seedListings: Listing[] = [
  listing({
    id: "land-cruiser-79",
    title: "Toyota Land Cruiser 79",
    price: 18500,
    category: "vehicles",
    country: "KE",
    city: "Nairobi",
    hoursAgo: 2,
    image: "/listings/cruiser.jpg",
    featured: true,
    badge: "featured",
    description:
      "Single-owner 70-series Land Cruiser, diesel, with a steel bumper, snorkel, and roof rack. Service history is with the Toyota dealer in Nairobi. Tyres have plenty of tread and the body is straight. Viewing in Kilimani this week, cash or bank transfer.",
    condition: "Used",
    sellerName: "James Otieno",
    sellerSince: "2019",
    phone: "+254 712 000 111",
  }),
  listing({
    id: "kigali-house",
    title: "2 bedroom house for rent",
    price: 450,
    priceSuffix: "/ month",
    category: "property",
    country: "RW",
    city: "Kigali",
    hoursAgo: 5,
    image: "/listings/villa.jpg",
    description:
      "Furnished two-bedroom house in Kiyovu with a pool shared by the compound, a fitted kitchen, and parking for one car. Utilities are separate. Available from the first of next month. Families and professionals welcome.",
    condition: "For rent",
    sellerName: "Aline Uwase",
    sellerSince: "2021",
    phone: "+250 788 220 014",
  }),
  listing({
    id: "macbook-pro-m2",
    title: "MacBook Pro M2",
    price: 750,
    category: "electronics",
    country: "TZ",
    city: "Dar es Salaam",
    hoursAgo: 1,
    image: "/listings/macbook.jpg",
    description:
      "13-inch MacBook Pro with the M2 chip, 16GB memory, and 512GB storage. Battery cycle count is under 200. Includes the original charger and a sleeve. Can meet in Masaki or post via DHL within Tanzania.",
    condition: "Like new",
    sellerName: "Hassan Juma",
    sellerSince: "2020",
    phone: "+255 754 118 903",
  }),
  listing({
    id: "john-deere-5075e",
    title: "John Deere 5075E Tractor",
    price: 32000,
    category: "agriculture",
    country: "ZM",
    city: "Lusaka",
    hoursAgo: 26,
    image: "/listings/tractor.jpg",
    description:
      "75hp utility tractor with a canopy, 4WD, and a front loader. About 1,800 hours. Used on a mixed farm outside Lusaka and serviced every season. Trailer and plough can be included for an extra fee.",
    condition: "Used",
    sellerName: "Mwansa Phiri",
    sellerSince: "2017",
    phone: "+260 97 440 2211",
  }),
  listing({
    id: "sofa-accra",
    title: "Sofa (like new)",
    price: 220,
    category: "home",
    country: "GH",
    city: "Accra",
    hoursAgo: 3,
    image: "/listings/sofa.jpg",
    description:
      "Three-seat fabric sofa in a light grey weave. Bought last year and kept in a non-smoking apartment in East Legon. No stains or sagging. Buyer collects, or I can arrange a small van in Accra.",
    condition: "Like new",
    sellerName: "Ama Boateng",
    sellerSince: "2023",
    phone: "+233 24 610 4488",
  }),
  listing({
    id: "iphone-14-pro",
    title: "iPhone 14 Pro",
    price: 680,
    category: "electronics",
    country: "KE",
    city: "Nairobi",
    hoursAgo: 4,
    image: "/listings/iphone.jpg",
    description:
      "Deep purple iPhone 14 Pro, 256GB, unlocked. Screen is original and the battery health is 91%. Comes with a box, cable, and a clear case. Happy to check the IMEI together before you pay.",
    condition: "Used",
    sellerName: "Grace Mwangi",
    sellerSince: "2022",
    phone: "+254 701 883 420",
  }),
  listing({
    id: "honda-crf-250l",
    title: "Honda CRF 250L",
    price: 2100,
    category: "vehicles",
    country: "UG",
    city: "Kampala",
    hoursAgo: 6,
    image: "/listings/dirtbike.jpg",
    description:
      "Red dual-sport Honda, registered and ridden mostly on weekend trails outside Kampala. New chain and sprockets this year. Starts first kick when cold. Logbook is ready and the bike can be tested in Ntinda.",
    condition: "Used",
    sellerName: "David Mugisha",
    sellerSince: "2018",
    phone: "+256 772 334 908",
  }),
  listing({
    id: "container-mombasa",
    title: "20ft shipping container",
    price: 2800,
    category: "business",
    country: "KE",
    city: "Mombasa",
    hoursAgo: 28,
    image: "/listings/container.jpg",
    description:
      "Wind and watertight 20ft dry container, cargo-worthy, sitting at a yard near the port. Suitable for storage or a site office. Delivery along the coast can be arranged. Inspection welcome before payment.",
    condition: "Used",
    sellerName: "Peter Kariuki",
    sellerSince: "2016",
    phone: "+254 722 901 334",
  }),
  listing({
    id: "logistics-coordinator",
    title: "Logistics Coordinator",
    price: 1200,
    priceSuffix: "/ month",
    category: "jobs",
    country: "KE",
    city: "Nairobi",
    hoursAgo: 2,
    image: "/listings/laptop.jpg",
    badge: "jobs",
    meta: "Full-time",
    description:
      "A Nairobi distributor is hiring a logistics coordinator to plan inbound trucks, chase deliveries, and keep the warehouse board up to date. You will need two years in freight or wholesale, clear English and Kiswahili, and comfort with spreadsheets. Medical cover after probation.",
    condition: "Full-time",
    sellerName: "Lilian Kamau",
    sellerSince: "2020",
    phone: "+254 733 221 087",
  }),
  listing({
    id: "farmland-arusha",
    title: "5 acres of farmland",
    price: 12000,
    category: "agriculture",
    country: "TZ",
    city: "Arusha",
    hoursAgo: 30,
    image: "/listings/farm.jpg",
    description:
      "Five acres of red soil with a seasonal stream along the south boundary, twenty minutes from Arusha town. Currently under maize. Title deed is clean and can be verified at the land office. Fencing is partial.",
    condition: "For sale",
    sellerName: "Neema Shao",
    sellerSince: "2015",
    phone: "+255 713 550 221",
  }),
  listing({
    id: "solar-panel-550",
    title: "Solar panel 550W",
    price: 350,
    category: "home",
    country: "RW",
    city: "Kigali",
    hoursAgo: 4,
    image: "/listings/solar.jpg",
    description:
      "New 550W monocrystalline panel, still in the carton, leftover from a rooftop job in Kimihurura. Suitable for 24V strings. I have four matching panels if you want a small array. Collection in Kigali.",
    condition: "New",
    sellerName: "Eric Habimana",
    sellerSince: "2021",
    phone: "+250 788 901 226",
  }),
  listing({
    id: "generator-lagos",
    title: "50kVA Diesel Generator",
    price: 5200,
    category: "business",
    country: "NG",
    city: "Lagos",
    hoursAgo: 26,
    image: "/listings/generator.jpg",
    description:
      "Silent-canopy 50kVA diesel set used as backup for a small cold room in Ikeja. About 3,200 hours, recently serviced, with a transfer switch available separately. You can hear it run before you commit.",
    condition: "Used",
    sellerName: "Chinedu Okonkwo",
    sellerSince: "2018",
    phone: "+234 803 441 2290",
  }),
  listing({
    id: "dining-nairobi",
    title: "Dining table set",
    price: 300,
    category: "home",
    country: "KE",
    city: "Nairobi",
    hoursAgo: 3,
    image: "/listings/dining.jpg",
    description:
      "Solid wood dining table with six chairs. Seats eight if you pull the chairs in. A few honest marks on the top, no wobble. Moving house in Lavington, so it needs to go this weekend.",
    condition: "Used",
    sellerName: "Wanjiku Njoroge",
    sellerSince: "2022",
    phone: "+254 715 662 104",
  }),
  listing({
    id: "hiace-2018",
    title: "Toyota Hiace (2018)",
    price: 9800,
    category: "vehicles",
    country: "TZ",
    city: "Dar es Salaam",
    hoursAgo: 5,
    image: "/listings/van.jpg",
    description:
      "2018 Hiace commuter, diesel, 14 seats, with a recent clutch and brake job. Used for a hotel shuttle, so the interior is tidy. Papers are in order. Test drive from Masaki by appointment.",
    condition: "Used",
    sellerName: "Fatima Hassan",
    sellerSince: "2019",
    phone: "+255 765 220 118",
  }),
  listing({
    id: "womens-clothing-bulk",
    title: "Women's clothing (bulk)",
    price: 25,
    category: "fashion",
    country: "GH",
    city: "Accra",
    hoursAgo: 6,
    image: "/listings/clothes.jpg",
    description:
      "Mixed bale of women's dresses and blouses, summer weights, sorted and wearable. Price is per small bundle of about eight pieces. Larger lots available for shops in Makola. No returns on bulk.",
    condition: "New",
    sellerName: "Efua Mensah",
    sellerSince: "2017",
    phone: "+233 20 448 7712",
  }),
  listing({
    id: "cat-320d",
    title: "CAT 320D Excavator",
    price: 48000,
    category: "business",
    country: "ZA",
    city: "Johannesburg",
    hoursAgo: 32,
    image: "/listings/excavator.jpg",
    description:
      "320D tracked excavator with a digging bucket and a hydraulic thumb. Undercarriage is at roughly 60%. Machine is working on a site in the East Rand and can be walked for a buyer. Service file comes with it.",
    condition: "Used",
    sellerName: "Thabo Nkosi",
    sellerSince: "2014",
    phone: "+27 82 445 1093",
  }),
  listing({
    id: "corolla-2016",
    title: "Toyota Corolla 2016",
    price: 8200,
    category: "vehicles",
    country: "KE",
    city: "Nairobi",
    hoursAgo: 8,
    image: "/listings/sedan.jpg",
    description:
      "2016 Corolla, petrol automatic, one local owner. Full service stamps, new front shocks, and a clean interior. Average fuel use around town. Viewing in Westlands after 5pm.",
    condition: "Used",
    sellerName: "Brian Odhiambo",
    sellerSince: "2020",
    phone: "+254 707 331 552",
  }),
  listing({
    id: "ranger-lusaka",
    title: "Ford Ranger double cab",
    price: 14500,
    category: "vehicles",
    country: "ZM",
    city: "Lusaka",
    hoursAgo: 48,
    image: "/listings/pickup.jpg",
    description:
      "Double-cab Ranger, diesel, canopy, and a tow bar. Used by a construction supervisor, so the bed has light scratches. Mechanically sound, air con cold. Can assist with Zambia–Botswana paperwork.",
    condition: "Used",
    sellerName: "Chanda Banda",
    sellerSince: "2016",
    phone: "+260 96 220 1184",
  }),
  listing({
    id: "bajaj-kampala",
    title: "Bajaj Boxer 150",
    price: 900,
    category: "vehicles",
    country: "UG",
    city: "Kampala",
    hoursAgo: 7,
    image: "/listings/scooter.jpg",
    description:
      "Boxer 150 used for boda work, recently rebuilt top end, new rear tyre. Registered in Kampala. Ideal as a second bike. Cash on inspection in Nakawa.",
    condition: "Used",
    sellerName: "Sarah Namuli",
    sellerSince: "2023",
    phone: "+256 701 228 441",
  }),
  listing({
    id: "house-accra",
    title: "3 bedroom house for sale",
    price: 89000,
    category: "property",
    country: "GH",
    city: "Accra",
    hoursAgo: 72,
    image: "/listings/house2.jpg",
    description:
      "Three bedrooms, two baths, a walled compound, and a boys' quarters in a quiet street near East Legon. Borehole and prepaid meter already in. Title search can be done with your lawyer before deposit.",
    condition: "For sale",
    sellerName: "Kwame Asante",
    sellerSince: "2015",
    phone: "+233 24 900 3312",
  }),
  listing({
    id: "studio-lagos",
    title: "Studio apartment, Ikeja",
    price: 380,
    priceSuffix: "/ month",
    category: "property",
    country: "NG",
    city: "Lagos",
    hoursAgo: 6,
    image: "/listings/apartment.jpg",
    description:
      "Self-contained studio with a kitchenette, prepaid power, and 24-hour security. Five minutes from the GRA. One month deposit and one month rent. Serious tenants only, no agents in the middle.",
    condition: "For rent",
    sellerName: "Zainab Bello",
    sellerSince: "2021",
    phone: "+234 809 112 3344",
  }),
  listing({
    id: "office-cape-town",
    title: "Small office in Woodstock",
    price: 1200,
    priceSuffix: "/ month",
    category: "property",
    country: "ZA",
    city: "Cape Town",
    hoursAgo: 20,
    image: "/listings/office.jpg",
    description:
      "42 square metres on the first floor, fibre-ready, with a shared boardroom and street parking. Suits a studio or a four-person team. Lease is one year. Available to view on weekdays.",
    condition: "For rent",
    sellerName: "Nadia Petersen",
    sellerSince: "2018",
    phone: "+27 72 880 4411",
  }),
  listing({
    id: "samsung-tv",
    title: "Samsung 55 inch TV",
    price: 420,
    category: "electronics",
    country: "ZA",
    city: "Johannesburg",
    hoursAgo: 9,
    image: "/listings/tv.jpg",
    description:
      "55-inch 4K Samsung, three years old, no dead pixels. Wall bracket included. Remote and power cable come with it. Collection in Rosebank.",
    condition: "Used",
    sellerName: "Lerato Dlamini",
    sellerSince: "2022",
    phone: "+27 83 220 7781",
  }),
  listing({
    id: "fridge-mombasa",
    title: "Double-door fridge",
    price: 180,
    category: "home",
    country: "KE",
    city: "Mombasa",
    hoursAgo: 5,
    image: "/listings/fridge.jpg",
    description:
      "Haier double-door fridge, frost free, cooling well. A small dent on the side that does not affect the seal. Ground-floor pickup in Nyali.",
    condition: "Used",
    sellerName: "Aisha Omar",
    sellerSince: "2019",
    phone: "+254 711 903 228",
  }),
  listing({
    id: "bed-kigali",
    title: "King bed and mattress",
    price: 150,
    category: "home",
    country: "RW",
    city: "Kigali",
    hoursAgo: 4,
    image: "/listings/bed.jpg",
    description:
      "Upholstered king frame with a medium mattress. Clean, non-smoking home in Remera. Must be collected. I can help carry it to a vehicle.",
    condition: "Used",
    sellerName: "Claire Ingabire",
    sellerSince: "2024",
    phone: "+250 788 330 119",
  }),
  listing({
    id: "teacher-accra",
    title: "Primary school teacher",
    price: 700,
    priceSuffix: "/ month",
    category: "jobs",
    country: "GH",
    city: "Accra",
    hoursAgo: 26,
    image: "/listings/classroom.jpg",
    badge: "jobs",
    meta: "Full-time",
    description:
      "A private primary in Cantonments needs a class teacher for grades 3–4. A teaching certificate and two years in the classroom are required. Classes run Monday to Friday, with a small Saturday club once a month.",
    condition: "Full-time",
    sellerName: "Adwoa Frimpong",
    sellerSince: "2016",
    phone: "+233 26 441 9088",
  }),
  listing({
    id: "sales-lagos",
    title: "Shop sales associate",
    price: 450,
    priceSuffix: "/ month",
    category: "jobs",
    country: "NG",
    city: "Lagos",
    hoursAgo: 8,
    image: "/listings/market.jpg",
    badge: "jobs",
    meta: "Full-time",
    description:
      "Electronics shop in Computer Village is hiring a sales associate who already knows phones and accessories. You will open the counter, keep stock counts, and follow up on WhatsApp orders. Six-day week.",
    condition: "Full-time",
    sellerName: "Tunde Adeyemi",
    sellerSince: "2019",
    phone: "+234 802 667 1190",
  }),
  listing({
    id: "plumbing-nairobi",
    title: "Plumbing call-out",
    price: 40,
    category: "services",
    country: "KE",
    city: "Nairobi",
    hoursAgo: 3,
    image: "/listings/tools.jpg",
    meta: "Call-out",
    description:
      "Licensed plumber covering Nairobi estates. The fee covers the visit and a basic diagnosis. Leaks, blocked drains, and geyser installs. Parts are quoted before any work starts. Same-day slots most weekdays.",
    condition: "Service",
    sellerName: "Joseph Maina",
    sellerSince: "2014",
    phone: "+254 720 118 663",
  }),
  listing({
    id: "braiding-accra",
    title: "Hair braiding at home",
    price: 15,
    category: "services",
    country: "GH",
    city: "Accra",
    hoursAgo: 2,
    image: "/listings/salon.jpg",
    meta: "From",
    description:
      "Knotless braids, cornrows, and twists done at my home salon in Osu or at yours within Accra. Price shown is the starting rate for a short style. Longer installs are quoted from a photo. Book a day ahead.",
    condition: "Service",
    sellerName: "Akosua Darko",
    sellerSince: "2022",
    phone: "+233 55 220 1844",
  }),
  listing({
    id: "moving-dar",
    title: "House moving, one truck",
    price: 80,
    category: "services",
    country: "TZ",
    city: "Dar es Salaam",
    hoursAgo: 22,
    image: "/listings/pickup.jpg",
    meta: "Per move",
    description:
      "One-ton pickup with two helpers for moves inside Dar es Salaam. The price covers a single load within the city, stairs included up to the third floor. Packing materials extra. Weekends fill up fast.",
    condition: "Service",
    sellerName: "Juma Ally",
    sellerSince: "2018",
    phone: "+255 713 880 442",
  }),
  listing({
    id: "dairy-cow-lusaka",
    title: "In-calf dairy cow",
    price: 650,
    category: "agriculture",
    country: "ZM",
    city: "Lusaka",
    hoursAgo: 6,
    image: "/listings/livestock.jpg",
    description:
      "Friesian cross, second lactation, confirmed in calf. Milking about 12 litres a day on grazing plus dairy meal. Healthy, dewormed last month. Transport from a farm south of Lusaka can be arranged.",
    condition: "Livestock",
    sellerName: "Ruth Zulu",
    sellerSince: "2013",
    phone: "+260 97 118 3340",
  }),
  listing({
    id: "maize-nakuru",
    title: "Maize seed, 50kg",
    price: 28,
    category: "agriculture",
    country: "KE",
    city: "Nakuru",
    hoursAgo: 4,
    image: "/listings/maize.jpg",
    description:
      "Certified hybrid maize seed, 50kg bags, this season's stock stored off the floor. Germination test sheet available. Discounts from ten bags. Pickup in Nakuru town or delivery in the Rift Valley.",
    condition: "New",
    sellerName: "Samuel Kiptoo",
    sellerSince: "2016",
    phone: "+254 726 441 908",
  }),
  listing({
    id: "ankara-kumasi",
    title: "Ankara fabric, 6 yards",
    price: 12,
    category: "fashion",
    country: "GH",
    city: "Kumasi",
    hoursAgo: 20,
    image: "/listings/clothes.jpg",
    description:
      "Wax print, six-yard pieces, current patterns. Price is per piece when you take five or more. Single pieces are slightly more. Photos of the exact prints sent on request. Ships from Kumasi.",
    condition: "New",
    sellerName: "Yaa Serwaa",
    sellerSince: "2020",
    phone: "+233 24 778 2201",
  }),
  listing({
    id: "sneakers-lagos",
    title: "Sneakers, mixed sizes",
    price: 18,
    category: "fashion",
    country: "NG",
    city: "Lagos",
    hoursAgo: 5,
    image: "/listings/market.jpg",
    description:
      "Carton of casual sneakers, mixed sizes 40–45, suitable for a stall. Price is per pair in lots of ten. Come and sort the carton in Trade Fair. No single-pair sales.",
    condition: "New",
    sellerName: "Ifeoma Eze",
    sellerSince: "2021",
    phone: "+234 806 220 1198",
  }),
  listing({
    id: "clinic-room-addis",
    title: "Consultation room to let",
    price: 500,
    priceSuffix: "/ month",
    category: "health",
    country: "ET",
    city: "Addis Ababa",
    hoursAgo: 40,
    image: "/listings/clinic.jpg",
    description:
      "A quiet consultation room inside a running clinic in Bole, with a shared waiting area and a nurse on the desk. Suitable for a GP or physiotherapist. Rent includes power and cleaning. One-year agreement.",
    condition: "For rent",
    sellerName: "Dr. Selam Bekele",
    sellerSince: "2017",
    phone: "+251 91 220 4481",
  }),
  listing({
    id: "nursing-kampala",
    title: "Home nursing visit",
    price: 25,
    category: "health",
    country: "UG",
    city: "Kampala",
    hoursAgo: 6,
    image: "/listings/clinic.jpg",
    meta: "Per visit",
    description:
      "Registered nurse available for wound care, blood pressure checks, and post-op visits at home in Kampala. The rate is per visit inside the city. Medication is not sold with the visit. Daytime hours.",
    condition: "Service",
    sellerName: "Mary Nakato",
    sellerSince: "2019",
    phone: "+256 782 110 663",
  }),
  listing({
    id: "textbooks-nairobi",
    title: "Form 4 textbook set",
    price: 35,
    category: "education",
    country: "KE",
    city: "Nairobi",
    hoursAgo: 3,
    image: "/listings/books.jpg",
    description:
      "Full set of current Form 4 course books: maths, English, Kiswahili, biology, chemistry, physics, and history. Light pencil notes in the margins, no missing pages. Ideal before exam term.",
    condition: "Used",
    sellerName: "Faith Chebet",
    sellerSince: "2024",
    phone: "+254 748 220 561",
  }),
  listing({
    id: "tutoring-kigali",
    title: "After-school maths tutoring",
    price: 15,
    priceSuffix: "/ hour",
    category: "education",
    country: "RW",
    city: "Kigali",
    hoursAgo: 5,
    image: "/listings/classroom.jpg",
    meta: "Evenings",
    description:
      "Secondary maths tutoring for senior 3 to senior 6, at my home in Kimironko or online. I am a qualified teacher with evening slots from Monday to Thursday. First session is a short assessment.",
    condition: "Service",
    sellerName: "Patrick Ndayisaba",
    sellerSince: "2018",
    phone: "+250 788 441 902",
  }),
  listing({
    id: "hall-maputo",
    title: "Community hall for hire",
    price: 40,
    priceSuffix: "/ day",
    category: "community",
    country: "MZ",
    city: "Maputo",
    hoursAgo: 24,
    image: "/listings/community.jpg",
    description:
      "Hall that seats about 80, with plastic chairs, a small stage, and a tap outside. Suitable for meetings, workshops, and family gatherings. No loud music after 9pm. Booking deposit holds the date.",
    condition: "For hire",
    sellerName: "Isabel Cossa",
    sellerSince: "2015",
    phone: "+258 84 220 1193",
  }),
  listing({
    id: "chairs-entebbe",
    title: "Plastic chairs, set of 40",
    price: 200,
    category: "community",
    country: "UG",
    city: "Entebbe",
    hoursAgo: 18,
    image: "/listings/dining.jpg",
    description:
      "Forty white plastic chairs from a church hall that is refurnishing. A few scuffs, all usable. Sold as one lot. Buyer collects from Entebbe. A pickup will do it in two trips.",
    condition: "Used",
    sellerName: "Robert Ssekandi",
    sellerSince: "2012",
    phone: "+256 772 880 221",
  }),
  listing({
    id: "hilux-gaborone",
    title: "Toyota Hilux 2014",
    price: 11000,
    category: "vehicles",
    country: "BW",
    city: "Gaborone",
    hoursAgo: 15,
    image: "/listings/pickup.jpg",
    description:
      "2014 Hilux single cab, petrol, canopy, and a bull bar. Straightforward farm and town use. Service book is stamped in Gaborone. No accident history that I know of. Test drive on the weekend.",
    condition: "Used",
    sellerName: "Kabelo Molefe",
    sellerSince: "2017",
    phone: "+267 72 110 448",
  }),
  listing({
    id: "cottage-windhoek",
    title: "Guest cottage, Klein Windhoek",
    price: 70,
    priceSuffix: "/ night",
    category: "property",
    country: "NA",
    city: "Windhoek",
    hoursAgo: 36,
    image: "/listings/house2.jpg",
    description:
      "One-bedroom cottage behind the main house, with a kitchenette, own entrance, and off-street parking. Weekly and monthly rates available. Quiet street, fibre installed. No parties.",
    condition: "For rent",
    sellerName: "Annette Shikongo",
    sellerSince: "2019",
    phone: "+264 81 220 3341",
  }),
  listing({
    id: "tailor-dakar",
    title: "Same-day alterations",
    price: 8,
    category: "services",
    country: "SN",
    city: "Dakar",
    hoursAgo: 12,
    image: "/listings/tools.jpg",
    meta: "From",
    description:
      "Trouser hems, dress taking-in, and zip replacements, usually the same day if you drop off before noon. The price is a simple hem. Wedding outfits are booked separately. Workshop in Plateau.",
    condition: "Service",
    sellerName: "Moussa Diop",
    sellerSince: "2011",
    phone: "+221 77 220 1184",
  }),
  listing({
    id: "cocoa-douala",
    title: "Cocoa seedlings, tray of 50",
    price: 15,
    category: "agriculture",
    country: "CM",
    city: "Douala",
    hoursAgo: 48,
    image: "/listings/maize.jpg",
    description:
      "Healthy cocoa seedlings in nursery bags, about four months old, ready to plant. Price is per tray of 50. Advice on spacing included. Collection from a nursery on the Douala–Yaoundé road.",
    condition: "New",
    sellerName: "Brigitte Ngo",
    sellerSince: "2016",
    phone: "+237 6 77 20 11 84",
  }),
  listing({
    id: "riad-room",
    title: "Riad room, medina",
    price: 95,
    priceSuffix: "/ night",
    category: "property",
    country: "MA",
    city: "Casablanca",
    hoursAgo: 10,
    image: "/listings/villa.jpg",
    description:
      "A quiet double room in a small riad, breakfast included, with a courtyard and fast wifi. Two-night minimum. Suitable for a work trip. The medina is a short walk.",
    condition: "For rent",
    sellerName: "Yasmine El Fassi",
    sellerSince: "2020",
    phone: "+212 661 220 448",
  }),
  listing({
    id: "arabic-cairo",
    title: "Arabic lessons for adults",
    price: 12,
    priceSuffix: "/ hour",
    category: "education",
    country: "EG",
    city: "Cairo",
    hoursAgo: 7,
    image: "/listings/books.jpg",
    meta: "Evenings",
    description:
      "Conversational Egyptian Arabic for adults, in person in Zamalek or on a video call. Beginners and people who froze after a course are both fine. Materials included. Evening slots.",
    condition: "Service",
    sellerName: "Omar Farouk",
    sellerSince: "2018",
    phone: "+20 100 220 4481",
  }),
  listing({
    id: "solar-lilongwe",
    title: "Solar starter kit",
    price: 190,
    category: "electronics",
    country: "MW",
    city: "Lilongwe",
    hoursAgo: 16,
    image: "/listings/solar.jpg",
    description:
      "200W panel, a 20A controller, and two LED bulbs. Enough for lights and phone charging in a small house. I can help with a simple roof mount in Lilongwe. New stock, warranty card in the box.",
    condition: "New",
    sellerName: "Tiwonge Banda",
    sellerSince: "2021",
    phone: "+265 999 220 118",
  }),
  listing({
    id: "catering-abidjan",
    title: "Event catering, trays",
    price: 60,
    category: "services",
    country: "CI",
    city: "Abidjan",
    hoursAgo: 9,
    image: "/listings/market.jpg",
    meta: "Per tray",
    description:
      "Jollof, grilled fish, and plantain trays for office lunches and family events in Abidjan. The price is one large tray that feeds about twelve. Order two days ahead. Delivery inside Cocody included.",
    condition: "Service",
    sellerName: "Aya Kouassi",
    sellerSince: "2019",
    phone: "+225 07 22 01 184",
  }),
  listing({
    id: "generator-hire-luanda",
    title: "Generator hire, weekend",
    price: 80,
    priceSuffix: "/ day",
    category: "business",
    country: "AO",
    city: "Luanda",
    hoursAgo: 14,
    image: "/listings/generator.jpg",
    description:
      "30kVA silent generator for events and site weekends in Luanda. Price is per day and includes delivery inside the city, diesel for eight hours, and a technician on call. Book before Thursday.",
    condition: "For hire",
    sellerName: "Paulo Mendes",
    sellerSince: "2015",
    phone: "+244 923 220 118",
  }),
  listing({
    id: "coffee-addis",
    title: "Yirgacheffe coffee, 1kg",
    price: 9,
    category: "agriculture",
    country: "ET",
    city: "Addis Ababa",
    hoursAgo: 8,
    image: "/listings/market.jpg",
    description:
      "Washed Yirgacheffe, roasted this week, packed in 1kg bags. Floral cup, light roast. Minimum four bags for delivery in Addis. Green beans available for roasters on request.",
    condition: "New",
    sellerName: "Hanna Tesfaye",
    sellerSince: "2020",
    phone: "+251 91 118 2204",
  }),
]

for (const item of seedListings) {
  const posted = seedPosting[item.id]
  if (!posted || !findSubcategory(item.category, posted.subcategory)) {
    throw new Error(`Posting plan missing for ${item.id}`)
  }
}
