import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { test } from "node:test"

function source(path: string): string {
  return readFileSync(new URL(`../${path}`, import.meta.url), "utf8")
}

test("F06 posting fields have stable labels, descriptions, group semantics, and focused error summary", () => {
  const field = source("src/components/form-field.tsx")
  const post = source("src/components/post-form.tsx")
  const location = source("src/components/posting/location-fields.tsx")
  assert.match(field, /useId/)
  assert.match(field, /htmlFor=\{controlId\}/)
  assert.match(field, /aria-describedby=\{describedBy\}/)
  assert.match(field, /<fieldset/)
  assert.match(field, /<legend/)
  assert.match(post, /id="post-error-summary"/)
  assert.match(post, /errorSummaryRef\.current\?\.focus\(\)/)
  assert.match(post, /id="post-title"/)
  assert.match(post, /id="post-price"/)
  assert.match(post, /id="post-description"/)
  assert.match(post, /aria-labelledby=\{labelledBy\}/)
  assert.match(location, /id="post-country"/)
  assert.match(location, /id="post-city"/)
  assert.match(location, /id="post-location-detail"/)
})

test("F07 account deletion is tombstoned, durable, retryable, and blocks new writes", () => {
  const worker = source("src/lib/account-deletion.ts")
  const session = source("src/lib/board-session.ts")
  const api = source("src/app/api/profile/route.ts")
  const cron = source("src/app/api/cron/expiry-reminders/route.ts")
  const sql = source("database/migrations/20261002_audit_f06_f10_hardening.sql")
  assert.ok(worker.indexOf('rpc("begin_board_account_deletion"') < worker.indexOf('rpc("cleanup_board_account_data"'))
  assert.ok(worker.indexOf('storage.from("listing-photos")') < worker.indexOf("auth.admin.deleteUser"))
  assert.match(worker, /markFailure/)
  assert.match(worker, /runAccountDeletionRetries/)
  assert.match(session, /isAccountDeletionPending\(data\.user\.id\)/)
  assert.match(api, /status: completed \? 200 : 202/)
  assert.match(cron, /runAccountDeletionRetries/)
  assert.match(sql, /for update skip locked/i)
  assert.match(sql, /reject_board_write_for_deleting_account/)
  assert.match(sql, /new writes are blocked/i)
})

test("F08 signed-out support intake is public, acknowledged, rate-limited, and operator-readable", () => {
  const page = source("src/app/contact/page.tsx")
  const form = source("src/components/support-request-form.tsx")
  const route = source("src/app/api/support/route.ts")
  const store = source("src/lib/support-store.ts")
  const admin = source("src/app/api/admin/support/route.ts")
  const sql = source("database/migrations/20261002_operational_hardening.sql")
  assert.match(page, /SupportRequestForm/)
  assert.doesNotMatch(page, /support unavailable/i)
  assert.match(form, /requestId/)
  assert.match(form, /role="status"/)
  assert.match(route, /sameOrigin/)
  assert.match(route, /429/)
  assert.match(store, /create_board_support_request/)
  assert.match(admin, /compliance:manage/)
  assert.match(sql, /board_support_requests/)
  assert.match(sql, />= 5/)
})

test("F09 published legal versions never expose unfinished placeholders and acceptance fails closed", () => {
  const terms = source("src/app/terms/page.tsx")
  const privacy = source("src/app/privacy/page.tsx")
  const legal = source("src/lib/legal.ts")
  const config = source("src/lib/legal-config.ts")
  const gate = source("src/lib/terms-gate.ts")
  const acceptance = source("src/lib/terms-acceptance.ts")
  for (const document of [terms, privacy]) {
    assert.doesNotMatch(document, /\[PLACEHOLDER|LAWYER TO CONFIRM|DRAFT|pending legal review/i)
  }
  assert.doesNotMatch(legal, /-draft/)
  assert.match(config, /LEGAL_DOCUMENTS_APPROVED/)
  assert.match(config, /LEGAL_OPERATOR_NAME/)
  assert.match(config, /LEGAL_OPERATOR_ADDRESS/)
  assert.match(config, /LEGAL_GOVERNING_LAW/)
  assert.match(config, /LEGAL_VENUE/)
  assert.match(gate, /publicationReady/)
  assert.match(acceptance, /published legal documents are not available for acceptance/)
})

test("F10 public browse is paginated and seller direct contact is listing-specific", () => {
  const inventory = source("src/lib/board-inventory.ts")
  const store = source("src/lib/board-store.ts")
  const board = source("src/app/api/board/route.ts")
  const listings = source("src/app/api/listings/route.ts")
  const contact = source("src/app/api/listings/[id]/contact/route.ts")
  const browse = source("src/components/browse.tsx")
  const detail = source("src/components/listing-detail.tsx")
  assert.match(inventory, /publicBoardPageSize = 48/)
  assert.match(inventory, /readPublicBoardPage/)
  assert.match(inventory, /limit\(publicBoardPageSize \+ 1\)/)
  assert.match(store, /readOwnedInventory/)
  assert.doesNotMatch(store, /readBoardInventory/)
  assert.match(store, /phone: ""/)
  assert.match(store, /board_contact_reveals/)
  assert.match(board, /listBoard\(owner\.id\)/)
  assert.match(listings, /listPublicBoardPage/)
  assert.match(contact, /contact:direct/)
  assert.match(contact, /requireCurrentTerms/)
  assert.match(browse, /Load more/)
  assert.match(detail, /\/contact/)
  assert.match(detail, /\?\? initialListing/)
})
